import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <head>
      <img src='/icon.png'></img>
    <link rel="icon" href="/icon.png" sizes="any" />
    </head>
      <body className={inter.className}>
      <div className="flex flex-col items-center">
        <div className="max-w-screen-md min-h-[100vh] w-full flex flex-col">

            

          {children}

          
        </div>
      </div>
      </body>
    </html>
  )
}
